### ISSUE TITLE
AMPLIFY_DIFF_BACKEND, AMPLIFY_DIFF_DEPLOY and [skip-cd] not working

### ISSUE THREAD

**Issue by frank-unovica** [aws-amplify/amplify-hosting#2145]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3hz155ieud30f

### Region

eu-central-1

### Amplify Console feature

Backend builds, Environment variables, Monorepo, Performance

### Describe the bug

According to https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html you should be able to set AMPLIFY_DIFF_BACKEND and AMPLIFY_DIFF_DEPLOY to true in the environment variables section of Amplify console and have only the frontend or backend built, depending on which files changed. Does not work.

And when you add [skip-cd] to a commit message, it should not trigger the automated build. Does not work.

Building is unacceptably slow due to pushing everything that already exists and not being able to select a decent EC2.

### Expected behavior

It should behave as documented.

### Reproduction steps

1. Create a project with automated build
2. Trigger automated build to see it works
3. Set environment variables or commit message as described above
4. Should not trigger but it does

### Build Settings

```yaml
version: 1
applications:
  - appRoot: pjk2
    backend:
      phases:
        preBuild:
          commands:
            - update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.8 11
            - /usr/local/bin/pip3.8 install --user pipenv
            - npm -v
            - node -v
            - nvm install 14
            - nvm use 14
            - npm -v
            - node -v
            - npm i -g yarn
            - yarn -v
            - npm i -g @aws-amplify/cli
        build:
          commands:
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - yarn -v
            - yarn
        build:
          commands:
            - yarn run build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
```

**Comment by Athena96** [comment]
Hi @frank-unovica I was unable to repro `[skip-cd]` it's working for me. 
I am looking into trying to repro the other issues you pointed out. thanks!

**Comment by Athena96** [comment]
Hi @frank-unovica I also tried `AMPLIFY_DIFF_DEPLOY` and I was unable to repro the issue. If I set `AMPLIFY_DIFF_DEPLOY` to true and click "Redeploy this Version" then the front end build is skipped.

It looks like your app is a monorepo. When you set these flags are you setting the root to your dirctory?
https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#enable-diff-deploy
`AMPLIFY_DIFF_DEPLOY_ROOT`

**Comment by frank-unovica** [comment]
I saw that later in the docs and set it, but didn't get around to it anymore - the [skip-cd] works now and probably the other ones too. It can be closed.

The root is already defined in AMPLIFY_MONOREPO_APP_ROOT, perhaps this can be used as a fallback value.

P.S. would be nice if the build time optimization is prioritized. The frontend & backend could be built on 2 separate machines in parallel. The lambda zip can be replaced on a code change (like the API and console do), rather than deleting and recreating resources that already exist. Or at least a simplified push for single-developer dev branches. Having these unnecessary slow deployment iterations (per customer in our case) slows down the whole development process. which makes us look bad and slows down the rest of the company.

**Comment by frank-unovica** [comment]
Actually [skip-cd] worked (at least once) but now it doesn't (I committed .gitattributes this way). Could it be that you have to add a message before [skip-cd] or does it have special handling for dot/git files? Is the source code of the automatic build publically viewable?

**Comment by Athena96** [comment]
@frank-unovica I noticed you are using CodeCommit. When I was attempting to repro I was using GitHub (which worked fine), but when I use CodeCommit I am having issues getting [skip-cd] working, so I am investigating this more and will get back.

**Comment by Athena96** [comment]
@frank-unovica I was able to repro with AMPLIFY_DIFF_DEPLOY + CodeCommit as well

**Comment by arledesma** [comment]
I am also using a monorepo and was unsuccessful at using `[skip-cd]` at the end of my commit message as specified at https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#skip-build-for-a-commit

Making a change to my `amplify.yml`, only targeting the change to one of my applications, I was wanting to manually build only that application, skipping the build and deploy of multiple other applications.

1. Is there specific placement of `[skip-cd]`?
2. Can there be a newline following `[skip-cd]`?
3. Can `[skip-cd]` be anywhere in the commit message?

**Comment by fullstackcreatives** [comment]
@Athena96 Is there an update on the issue with using [skip-cd] on CodeCommit? Seems that it still does not work.

**Comment by hloriana** [comment]
Hi @fullstackcreatives 👋🏽, thank you for reaching out and apologies for the delay. We are prioritizing this bug and are working on  a fix. Thank you for your patience!

**Comment by mauerbac** [comment]
Hi @hloriana - I think this issue has been resolved. I was able to confirm setting `AMPLIFY_DIFF_DEPLOY` did not trigger a deploy.

**Comment by Athena96** [comment]
Closing this out as this issue is resolved now. Please feel free to re-open if you continue to face the issue. Thanks!

**Comment by turmspringer** [comment]
Hi @Athena96, unfortunately `[skip-cd]` is still not working with CodeCommit. Can you (or someone else) please reopen this issue?

**Comment by JDHalm** [comment]
@Athena96 @hloriana we are not able to get `AMPLIFY_DIFF_DEPLOY` to work on our application. We're running a static Nuxt build, rebuilding without changing any files causes a full rebuild rather than a skip. Can we get this issue re-opened?

**Comment by dchanmaisonette** [comment]
@Athena96 In github commit message, adding [skip-cd] also doesn't work, is that expected behavior?
