### ISSUE TITLE
503 issues on every api route with Nextjs 11

### ISSUE THREAD

**Issue by newilu** [aws-amplify/amplify-hosting#2518]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:eu-west-1:114719936836:apps/dwyqpdfjrd4u5

### Region

eu-west-1

### Amplify Console feature

Backend builds, Build settings

### Describe the bug

After build every request to /api/* fails with 503 error. Locally with "next dev" and "next build && next start" commands running I'm not getting this issue.
I've tried to give my lambda&edge functions roles such as AdministratorAccess-Amplify and AdministratorAccess - not worked.
Tried to recreate whole app (including services connected like  cognito & appsync) with cli (amplify init) and manually from console - not worked.
Tried to switch nextjs version from 12 to 11 and node from 14 to 12 and back - not worked.
About 2 months ago all of my api routes worked fine, after it i left the project, there was no commits and rebuilds at all and when i'm back im seeing this issue.

### Expected behavior

Expected behavior was app works after build as fine as locally.

### Reproduction steps

Open the link https://development.d2959ba1d856u5.amplifyapp.com/ and open dev console so you can see 503 errors on "sites" and other /api/* routes.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - nvm use $VERSION_NODE_14
        - npm ci
    build:
      commands:
        - nvm use $VERSION_NODE_14
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by manuarora700** [comment]
I'm able to create an account and get a `200` response from Cognito by exactly following the steps mentioned by you.

**Comment by newilu** [comment]
> I'm able to create an account and get a `200` response from Cognito by exactly following the steps mentioned by you.

well, i said about /api routes man, not cognito requests)

**Comment by newilu** [comment]
also i noticed that this only appears on routes that works with dynamodb

**Comment by rakshithxaloori** [comment]
@newilu I'm facing the same issue. Any luck fixing the errors?

**Comment by Narrator** [comment]
@rakshithxaloori @newilu We are currently looking into this, but can you please provide us with the access logs from the Lambda@Edge functions deployed in your AWS accounts?

You can find the steps to pull access logs by following this link: https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#access-lambda-edge-logs

**Comment by bbarbour** [comment]
here is an example from the logs on my side
[log-events-viewer-result(1).csv](https://github.com/aws-amplify/amplify-hosting/files/8273165/log-events-viewer-result.1.csv)

**Comment by bbarbour** [comment]
[3_16_2022-access-logs.csv](https://github.com/aws-amplify/amplify-hosting/files/8273373/3_16_2022-access-logs.csv)
full amplify log

**Comment by rakshithxaloori** [comment]
@Narrator Thank you for responding. It was an issue in my env variables. I fixed it and the 503 errors are gone. Should I go ahead and delete my previous comment?

**Comment by bbarbour** [comment]
what was the change?

**Comment by rakshithxaloori** [comment]
I had to change some env variables to PUBLIC. Then it was resolved

**Comment by bbarbour** [comment]
I don't think that's the same problem as for me, still getting 503 even without any env variables defined

**Comment by bbarbour** [comment]
@Narrator any thoughts on this? sites remain broken

**Comment by bbarbour** [comment]
my problem is resolved - noticed next was upgraded to v12 - which is obviously not yet supported in amplify

**Comment by fgrs** [comment]
@bbarbour where do you find info on what latest version of nextjs is supported?

**Comment by bbarbour** [comment]
This article calls out v11 specifically, but nothing on v12.  https://aws.amazon.com/about-aws/whats-new/2021/08/aws-amplify-hosting-support-next-js-version-11/

- check package.json dependencies 
        "dependencies": {
          **"next": "^11.1.4",**   <<<-----
          "react": "17.0.2",
          "react-dom": "17.0.2"
        },
- run npm install next@11 
- fixed the deployment

capabilities in next v12 https://nextjs.org/blog/next-12#introducing-middleware

**Comment by bbarbour** [comment]
Yes it was resolved by downgrading

**Comment by victorccccc** [comment]
Hi, sorry for the convenience. Currently, Amplify doesn't support Next 12. If you are seeing 503 error in Next 12, please try to downgrade to Next 11.

If you are already in Next 11 or lower version, please follow this instruction to attach logs here https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#access-lambda-edge-logs . Thanks

**Comment by MatheusChein** [comment]
@victorccccc does it work if we override the package version on the build settings? And set it to NextJs v11? Or do we also have to change that on the package.json file of the project?

**Comment by hloriana** [comment]
For anyone experiencing this 503 bug, please try to redeploy your SSR app. We just rolled out an update that should fix this issue.

**Comment by foobarnes** [comment]
For anyone who gets here and is still getting a 503 error,  my issue was forgetting to configure Amplify in each of my API routes in NextJS 🤦🏻 

[Example](https://aws.amazon.com/blogs/mobile/ssr-support-for-aws-amplify-javascript-libraries/#:~:text=//%20Amplify%20SSR%20configuration%20needs%20to%20be%20done%20within%20each%20API%20route%0AAmplify.configure(%7B%20...config%2C%20ssr%3A%20true%20%7D)%3B)
